import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/Contact'
import Layout from '../components/Layout'
import MobileMenu from '../components/MobileMenu'
import Services from '../components/Services'
import TopSection from '../components/TopSection'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Layout>
        <TopSection />
        <Services />
        <Contact />
      </Layout>
    </div>
  )
}
